name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: pnpm -C pascas-labs-site install
      - run: pnpm -C pascas-labs-site lint
      - run: pnpm -C pascas-labs-site build
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium
      - name: Run E2E
        run: pnpm -C pascas-labs-site test:e2e:ci
        env:
          BASE_URL: http://localhost:3000

