name: Deploy Static to IONOS
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pascas-labs-site
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: pascas-labs-site/pnpm-lock.yaml
      - run: pnpm install
      - name: Build (static export)
        run: pnpm build
        env:
          NEXT_PUBLIC_SITE_URL: ${{ vars.NEXT_PUBLIC_SITE_URL }}
          NEXT_PUBLIC_PLAUSIBLE_DOMAIN: ${{ vars.NEXT_PUBLIC_PLAUSIBLE_DOMAIN }}
      - name: Upload via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.IONOS_SFTP_HOST }}
          username: ${{ secrets.IONOS_SFTP_USER }}
          password: ${{ secrets.IONOS_SFTP_PASS }}
          local_path: "./out/*"
          remote_path: "/public_html"
          delete_remote_files: true

