name: Deploy Static to IONOS
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: pascas-labs-site
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Enable pnpm via corepack
        run: |
          corepack enable
          corepack prepare pnpm@9 --activate
      - name: Install deps
        run: pnpm install
        working-directory: pascas-labs-site
      - name: Build (static export)
        run: pnpm build
        working-directory: pascas-labs-site
        env:
          NEXT_PUBLIC_SITE_URL: ${{ vars.NEXT_PUBLIC_SITE_URL }}
          NEXT_PUBLIC_PLAUSIBLE_DOMAIN: ${{ vars.NEXT_PUBLIC_PLAUSIBLE_DOMAIN }}
      - name: Upload via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.IONOS_SFTP_HOST }}
          username: ${{ secrets.IONOS_SFTP_USER }}
          password: ${{ secrets.IONOS_SFTP_PASS }}
          local_path: "pascas-labs-site/out/*"
          remote_path: "/public_html"
          delete_remote_files: true

